### ISSUE TITLE
Tighten file permissions

### ISSUE THREAD

**Issue by jobhh** [poralix/directadmin-teach-sa#7]
Since issue #3 has been closed it is now possible to set file permissions similar to other scripts without breaking the plugin.

After `git clone https://github.com/poralix/directadmin-teach-sa.git` the following folder/file permissions are set by default:

    drwxr-xr-x
    -rwxr-xr-x

I ran `chmod -R 700 directadmin-teach-sa/` and tested the script. These permissions also function fine now:

    drwx------
    -rwx------ 

Updating the permissions of the files/folder in the repository seems the best option to me, but adding the chmod to the manual is also possible.

Somewhat related:
I've also set `chown -R diradmin:diradmin directadmin-teach-sa/` to change the owner from my root user to diradmin. This way DirectAdmin has access to the script if functionality that requires this is ever added. cron_sa_learn.log is of course created as root when the script is ran the first time, but the owner remains diradmin if it is changed once. Adding a dummy cron_sa_learn.log circumvents this issue.

**Comment by poralix** [comment]
Hello,

Directadmin does not use directadmin-teach-sa at all. 

The script _cron_sa_learn.sh_ is designed to allow regular users to run it too. In order to allow your users to run the script it should be placed somewhere else outside of /usr/local/directadmin/scripts/.

Whatever permissions you set for files and folders under /usr/local/directadmin/scripts/ they will be changed by directadmin's update process. Every time when Directadmin is updated it will set everything under /usr/local/directadmin/scripts/ to 700 and owned by diradmin:diradmin.

You can by the way store directadmin-teach-sa under /root, e.g. in /root/directadmin-teach-sa or under /usr/local, e.g. in /usr/local/directadmin-teach-sa, or /opt, etc.

If the script is executed not by root it will run only for one user, exactly for that user that executed the script.

So you are free to use any permissions you want. Just make sure the *.sh scripts have execute permission at least for user root, and at least 555 if you want to allow your users to run it.

Regards,
Alex.

**Comment by jobhh** [comment]
Ok, I didn't know Directadmin sets everything under /usr/local/directadmin/scripts/ to 700 and owned by diradmin:diradmin. It's possible that is happened automatically and I didn't change the permissions myself, even better that #3 is fixed then :)

Thanks for the quick explanation!
